### ISSUE TITLE
Custom Datasets

### ISSUE THREAD

**Issue by WHHHHY** [RuyiLian/CheckerPose#4]
Thanks for your  excellent work!
And if I want train my customized datasets made in linemod format，how should I modify the paths and codes?

**Comment by RuyiLian** [comment]
Thanks for your interest of our work!
I assume that you would like to use a single network to predict multiple objects simultaneously, like our Linemod experiments reported in the paper. For this dataset we have separate files for dataset loading , training and testing . 

Dataset codes are mainly in `checkerpose/tools_for_LM/get_lm_datasets.py` and `checkerpose/lm_dataset_pytorch.py`. The dataset paths can be modified in `checkerpose/tools_for_LM/get_lm_datasets.py`.
Training codes can be found in `checkerpose/pretrain_lm.py` and `checkerpose/train_lm.py`. (The name of `pretrain` is kind of misleading, it actually means training only the low level layers of the whole network.) And test file is `checkerpose/test_lm.py`. For these files, reset the dataset related codes. 
Also, write new configs similar to `checkerpose/config/lm/init_gnn2_hrnetw18_npt512_lm.txt` (for pretrain) and `checkerpose/config/lm/hr18GNN2_res6_gnn3Skip_mlpQuery_lm.txt` (for train).

For Linemod experiments, we use two training subsets. One is the images from BOP website, and the other one is a synthetic dataset downloaded from GDR-Net GitHub repo. You may need to write
```
training_data_folder_2 = none
```
in your config files if you only have one single training subset.

Also, in our default setting, we randomly reset the background images
https://github.com/RuyiLian/CheckerPose/blob/fb725bed2a9eb6c3646c476c017d9ad00aa63a28/checkerpose/config/lm/hr18GNN2_res6_gnn3Skip_mlpQuery_lm.txt#L11
We use `VOC 2012` as background images. The details can be found in our `README` (data preparation, 2 and 4)
You can just discard codes of changing background if it is unnecessary.

**Comment by WHHHHY** [comment]
Thanks for your patient reply!
 In fact, I am training only one customized object.But I met some questions after reset the dataset related codes.
1.How to generate "bbox_faster_all.json" for my obj（
My object is a custom object）.  
2.What's difference between  "bbox_faster_all.json"  and "bbox_yolov3_all.json"？   Have a nice day！

**Comment by RuyiLian** [comment]
Those `.json` files are object detection results (bounding boxes) for the test samples. During training, the cropped RoI image is generated by augmenting the ground truth annotations.
I use the detection results provided by [GDR-Net](https://github.com/THU-DA-6D-Pose-Group/GDR-Net). `bbox_yolov3_all.json` uses Yolov3 detector, while `bbox_faster_all.json` uses  Faster-RCNN detector. Based on the experiment results, the latter one has higher accuracy.

**Comment by WHHHHY** [comment]
Thanks a lot,I will try it!

**Comment by WHHHHY** [comment]
Sorry for bother you again.
I noticed that "dataset_dicts_lm_13_train_d7ed50dadc7fbec7f5a406725d6978bd.pkl" was loaded in stage of training.
Is this pkl file only for replacing the background of the image?And if i don't need it，what should I do.

**Comment by RuyiLian** [comment]
The file `dataset_dicts_lm_13_train_d7ed50dadc7fbec7f5a406725d6978bd.pkl` is used to speed up loading the training sets. This can be modified in 
https://github.com/RuyiLian/CheckerPose/blob/fb725bed2a9eb6c3646c476c017d9ad00aa63a28/checkerpose/tools_for_LM/get_lm_datasets.py#L55-L67

Option 1: modify the `hashed_file_name` to load your own data instead of LM dataset.
Option 2: remove the codes containing `cache_path` in `checkerpose/tools_for_LM/get_lm_datasets.py`, thus you will not accidentally load wrong cached data.

**Comment by WHHHHY** [comment]
I encountered the following error when running pretrain_lm.py. Why is a 500-image image loaded here for testing? Can you give me some suggestions about this error?This bug has indeed been bothering me for a few days  :(    ![image](https://github.com/user-attachments/assets/bd926b08-32b5-4a30-b11b-88f16368a164)
The complete error report is as follows:
#parameters: 11.490075M
2024-07-27 23:45:27.607234 init_gnn2_hrnetw18_npt512_lm  iteration_step: 0 loss_mask_bit: 0.5915180444717407 loss_proj_bit_x: 0.9953179359436035 loss_proj_bit_y: 0.8112733960151672 loss: 2.3981094360351562 time: 1.110907s est: 15.429h
test dataset
 13%|███████████▍                                                                             | 64/500 [00:06<00:40, 10.66it/s]
Traceback (most recent call last):
  File "pretrain_lm.py", line 303, in <module>
    main(configs)
  File "pretrain_lm.py", line 258, in main
    test_init_lm(net, test_loader, writer, iteration_step, configs, best_score_metric="mean_bit_acc")
  File "/root/autodl-tmp/hongyang/CheckerPose-main/checkerpose/test_network_with_test_data.py", line 222, in test_init_lm
    roi_mask_bits, pixel_x_codes, pixel_y_codes, roi_xy_oris) in enumerate(tqdm(dataloader)):
  File "/root/autodl-tmp/conda/envs/checker/lib/python3.7/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/root/autodl-tmp/conda/envs/checker/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/root/autodl-tmp/conda/envs/checker/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/root/autodl-tmp/conda/envs/checker/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/root/autodl-tmp/conda/envs/checker/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/autodl-tmp/conda/envs/checker/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/autodl-tmp/conda/envs/checker/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/root/autodl-tmp/conda/envs/checker/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 84, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/root/autodl-tmp/conda/envs/checker/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 84, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/root/autodl-tmp/conda/envs/checker/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 53, in default_collate
    numel = sum(x.numel() for x in batch)
  File "/root/autodl-tmp/conda/envs/checker/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 53, in <genexpr>
    numel = sum(x.numel() for x in batch)
AttributeError: 'numpy.ndarray' object has no attribute 'numel'

**Comment by WHHHHY** [comment]
I found that these values in "class lm dataset single obj pytorch code2d(Dataset)" are not converted to tensor type, they are still numpy.ndarry. :
![image](https://github.com/user-attachments/assets/9de548e7-2b8c-4082-9773-fffcb07ad645)

**Comment by RuyiLian** [comment]
1. I guess there should be 500 batches loaded for testing, since `batch_size=8` in 
https://github.com/RuyiLian/CheckerPose/blob/fb725bed2a9eb6c3646c476c017d9ad00aa63a28/checkerpose/pretrain_lm.py#L137C61-L137C73
(since `drop_last=False` for data loader, there should be at most 4,000 images)

2. I agree that they should be converted to tensor types for consistency. The original codes may cause trouble for unexpected cases (e.g. there is no detection results). You can add some codes like `R = torch.from_numpy(R).type(torch.float)`

**Comment by WHHHHY** [comment]
With your patient help, I have trained this network using my dataset! But now I have some new problems.
1. The LOSS fluctuates during very serious training except mask_loss, probably because the geometry of my object is very complex.
2. I did not find the "flattening" operation in the code, it should be between backbone and 1D conv. Maybe I was careless.
Have a nice day  :)

**Comment by RuyiLian** [comment]
1. I am not sure how to solve this problem for a very complex object. Have you tried the following solutions?
(1) adjust the learning rate (2) set different weight for different loss (3) for the binary code loss, print loss of each bit and see from which bit the training is unstable

2. In implementation I actually first apply a 2D convention with 1x1 kernel and then flatten the feature (`out.view(...)`). Theoretically this implementation is equivalent to the process mentioned in the paper. 
https://github.com/RuyiLian/CheckerPose/blob/fb725bed2a9eb6c3646c476c017d9ad00aa63a28/checkerpose/model/init.py#L112-L114

**Comment by WHHHHY** [comment]
I found this error because my custom model.ply  had wrong units.,it should be mm.After fixing this, I finally trained the checkerpose, But only got ACC in the pre-training stage, as shown below:
![image](https://github.com/user-attachments/assets/c3221f51-fd48-41cb-af26-5f3dfd401199)
In the train stage,there is no ACC anymore:
![image](https://github.com/user-attachments/assets/1dda52ef-b523-4c46-a025-54d955e6ea5b)
I find that  pred_rot, pred_trans is wrong,and always like this:
![image](https://github.com/user-attachments/assets/89078432-4cbb-46d5-9baa-390037cabcbd)
And Some coordinates of "valid_disc_p2d" seems like exceed the original image size:
![image](https://github.com/user-attachments/assets/6ff02787-e78d-4ad3-a71d-63ebce9a8813)
Would you give me some adices,Thx a lot.

**Comment by WHHHHY** [comment]
Hi,I finally trained my datasets using Checkerpose under your patient help.
But When i set the "Detection_reaults " to 'none',adx10 index almost close to 0.998.Overfitting has occured.
 I noticed that there are no detection results for  test data ,only the train data,so could you tell me What's the difference with "Detection_reaults " in pretrain ,train or test,:
[https://github.com/RuyiLian/CheckerPose/blob/fb725bed2a9eb6c3646c476c017d9ad00aa63a28/checkerpose/test_lm.py#L92](url)
`Detection_reaults = configs['Detection_reaults']  # for the test, the detected bounding box provided by GDR Net
`
This is my training log and Acc index：
![image](https://github.com/user-attachments/assets/e13c24b6-1a18-4bd3-8671-4753af2959db)
![image](https://github.com/user-attachments/assets/2f686e25-cf95-4dda-9e9a-7e22a428bef1)

**Comment by RuyiLian** [comment]
To load the datasets, I modify the codes of GDR-Net and ZebraPose. For BOP datasets such as LM, setting "Detection_reaults " to 'none' will load ground truth bounding boxes provided by the dataset annotations, as shown in the function https://github.com/RuyiLian/CheckerPose/blob/fb725bed2a9eb6c3646c476c017d9ad00aa63a28/checkerpose/lm_dataset_pytorch.py#L355

**Comment by WHHHHY** [comment]
Thanks，I got it
